Repository guibranco/VTEX-SDK-dotnet, pull requests merged in 2023-11, with the labels that each got.

#187 Install .NET 8 in AppVeyor
  Tests/VTEX.Tests/VTEX.Tests.csproj
  appveyor.yml
Labels: enhancement, CI/CD, dependencies, .NET, size/XS

#186 Add explicitly support to .NET 6, .NET 7 and .NET 8
  Src/VTEX.API/VTEX.API.csproj
  Src/VTEX.Core/VTEX.Core.csproj
  Src/VTEX.Health/VTEX.Health.csproj
  Src/VTEX/VTEX.csproj
Labels: size/XS

#189 Update qodana.yml
  .github/workflows/qodana.yml
Labels: size/S
